#!/usr/bin/env perl

use warnings;
use strict;

use Getopt::Long qw(:config bundling no_ignore_case pass_through);
use Net::ZooKeeper qw(:node_flags :acls :errors);

GetOptions(
  my $opts = {},
  'address|A=s',
);

my $path  = shift @ARGV || '/';
my $zkh   = Net::ZooKeeper->new($opts->{address} || 'localhost:18121');

sub dumptree
{
  my ($node,$indent) = @_;
  if (!defined $indent) {
    $indent=0;
    print "node $node has child nodes:\n";
  }
  foreach my $path (sort $zkh->get_children($node)) { 
    my $p = $node . "/" . $path;
    $p = "/" . $path if($node eq '/');
    my $contents = $zkh->get($p);
    if (defined $contents && $contents ne '') {
      printf("%*s%s: %s\n", $indent, '', $path, $contents);
    } else {
      printf("%*s%s\n", $indent, '', $path);
    }
    dumptree($p, $indent+2);
  }
}

dumptree($path);
