#!/usr/bin/env perl

use warnings;
use strict;

use Getopt::Long qw(:config bundling no_ignore_case pass_through);
use Net::ZooKeeper qw(:node_flags :acls :errors);

GetOptions(
  my $opts = {},
  'address|A=s',
);

my $path  = shift @ARGV || die "usage: $0 [-A zkaddr] <path>\n";
my $zkh   = Net::ZooKeeper->new($opts->{address} || 'localhost:18121');

sub nuketree
{
  my ($node,$indent) = @_;
  if(!defined $indent) {
    $indent=0;
    print "removing node $node:\n";
  }
  foreach my $path ($zkh->get_children($node)) {
    my $p = $node . "/" . $path;
    $p = "/" . $path if($node eq '/');
    print("$p\n");
    nuketree($p, $indent+2);
  }
  $zkh->delete($node);
}

nuketree($path);
