#!/usr/bin/env perl -w

# Copyright (c) 2010-2011 Yahoo! Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use common::sense;

use AnyEvent;
use YAML::XS qw(LoadFile);
use FindBin qw($Bin);
use Log::Log4perl qw(:easy);

use lib "$Bin/lib";
use lib "$Bin/../lib";

use PogoDummyWorker;

Log::Log4perl::init("$Bin/conf/log4perl.conf");
chdir($Bin);

$PogoDummyWorker::opts = LoadFile("conf/worker.conf");

$PogoDummyWorker::opts->{num_workers} = 2;

$PogoDummyWorker::execute = sub {
  my ( $self, $task_id ) = @_;
  my @lines = ( "Fuck you, whale!\n", "Fuck you, dolphin!\n" );
  foreach (@lines)
  {
    $self->write_output_entry( { task => $task_id, type => 'STDOUT' }, $_ );
  }

  $self->reset( $task_id, 0 );    # DO NOT EXIT THIS SUB WITHOUT CALLING RESET!
};

my $worker = PogoDummyWorker::instance()
  or LOGCONFESS;

#$worker->run(); # This is a real Pogo::Worker object

# Let's do our own AnyEvent loop

$worker->connect( 1, 1 );
AnyEvent->condvar->recv();

1;

=pod

=head1 NAME

  CLASSNAME - SHORT DESCRIPTION

=head1 SYNOPSIS

CODE GOES HERE

=head1 DESCRIPTION

LONG_DESCRIPTION

=head1 METHODS

B<methodexample>

=over 2

methoddescription

=back

=head1 SEE ALSO

L<Pogo::Dispatcher>

=head1 COPYRIGHT

Apache 2.0

=head1 AUTHORS

  Andrew Sloane <andy@a1k0n.net>
  Michael Fischer <michael+pogo@dynamine.net>
  Mike Schilli <m@perlmeister.com>
  Nicholas Harteau <nrh@hep.cat>
  Nick Purvis <nep@noisetu.be>
  Robert Phan <robert.phan@gmail.com>

=cut

# vim:ts=2:sw=2:syntax=perl
