#!/usr/bin/env perl
# Copyright (c) 2010, Yahoo! Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use 5.008;
use common::sense;

use FindBin qw($Bin);

use lib "$Bin/../lib";
use lib "$Bin/../t/lib";

use PogoTester;

sub start
{
  $ENV{POGO_PERSIST} = 1;
  PogoTester::start_zookeeper();
  PogoTester::start_dispatcher();
  PogoTester::start_worker();
}

sub stop
{
  delete $ENV{POGO_PERSIST};
  PogoTester::stop_worker();
  PogoTester::stop_dispatcher();
  PogoTester::stop_zookeeper();
}

sub restart
{
  stop();
  start();
}

sub main
{
  if ($ARGV[0] eq 'start')
  {
    start();
    return 0;
  }
  elsif ($ARGV[0] eq 'stop')
  {
    stop();
    return 0;
  }
  elsif ($ARGV[0] eq 'restart')
  {
    restart();
    return 0;
  }

  print "what?";
}

exit &main;

1;

=pod

=head1 NAME

  CLASSNAME - SHORT DESCRIPTION

=head1 SYNOPSIS

CODE GOES HERE

=head1 DESCRIPTION

LONG_DESCRIPTION

=head1 METHODS

B<methodexample>

=over 2

methoddescription

=back

=head1 SEE ALSO

L<Pogo::Dispatcher>

=head1 COPYRIGHT

Apache 2.0

=head1 AUTHORS

  Andrew Sloane <andy@a1k0n.net>
  Michael Fischer <michael+pogo@dynamine.net>
  Mike Schilli <m@perlmeister.com>
  Nicholas Harteau <nrh@hep.cat>
  Nick Purvis <nep@noisetu.be>
  Robert Phan robert.phan@gmail.com

=cut

# vim:syn=perl:sw=2:ts=2:sts=2:et:fdm=marker
